### ISSUE TITLE
Intéressés pour venir nous parler de la tech blablacar ?

### ISSUE THREAD

**Issue by youribonnaffe** [blablacar/blablatech#10]
Hello,

Nous avons récemment ouvert le CFP pour [Riviera DEV 2016](http://rivieradev.fr/), la conférence des développeurs au soleil qui se tiendra le 16 et 17 juin à Sophia-Antipolis.

Personnellement je trouverais super chouette d'avoir un speaker de chez blablacar pour nous parler de ce que vous faites que ça soit côté mobile, web ou serveur. N'hésitez pas à nous soumettre des propositions de talks : https://www.papercall.io/rivieradev-2016

Au plaisir de vous voir à Riviera DEV !

**Comment by ErwannRobin** [comment]
vu que l'évènement est passé, je clos

**Comment by youribonnaffe** [comment]
Si jamais l'événement a lieu cette année : http://rivieradev.fr

Le 30 janv. 2017 4:48 PM, "Erwann Robin" <notifications@github.com> a
écrit :

**Comment by ErwannRobin** [comment]
ok, je transmet
