### ISSUE TITLE
Absolute path for all images

### ISSUE THREAD

**Issue by j0k3r** [blablacar/blablatech#5]
Will it be possible in the future to put absolute path to all images ?

This:

```
![](http://blablatech.com/images/2015-02-16_coding-night-in-blablacar/IMG_0268.JPG =600x)
```

Instead of this:

```
![](/images/2015-02-16_coding-night-in-blablacar/IMG_0268.JPG =600x)
```

It will avoid RSS feeds to not display them correctly :)
Thanks!

**Comment by MattKetmo** [comment]
Hmm, your RSS can't handle this correctly?
I've seen nobody putting an absolute path in static blog images. Plus I doesn't play well when you use it locally (the content of a blog should not depends on a domain name).

I'm :-1:

**Comment by j0k3r** [comment]
My RSS reader doesn't handle it sadly.

![image](https://cloud.githubusercontent.com/assets/62333/6960278/600ea222-d921-11e4-92e2-d253e8900cd1.png)

BUT, I guess this is because paths were wrong, regarding https://github.com/blablacar/blablatech/commit/cb9d98735b5825debd5d082f311b5880619e86e0

And since feedly seems to cache html of the feed item, the blog post still look bad.
Anyway
